--password-store=gnome-libsecret --use-gl=angle --use-angle=gl \
--enable-features=AcceleratedVideoEncoder,AcceleratedVideoDecodeLinuxGL,VaapiOnNvidiaGPUs,VaapiVideoDecoder,VaapiIgnoreDriverChecks \
--ignore-gpu-blocklist --disable-gpu-driver-bug-workaround --disable-features=Vulkan
